Redirect release calendar URLs to proxy
ONSdigital/dp-frontend-router pull request #451
Opened 2024-03-05 14:41 UTC by jakeandandrews

### What

When LegacyCacheProxyEnabled is true release calendar URLs are redirected to dp-legacy-cache-proxy 

### How to review

1. Run dp-frontend-release-calendar with the required apps mentioned in its README
2. Run dp-frontend-router make debug and set LEGACY_CACHE_PROXY_ENABLED=true
6. This requires changes that are part of https://github.com/ONSdigital/dp-legacy-cache-proxy/pull/4 in order to check that the call is made to the dp-legacy-cache-proxy. Checkout the [branch](https://github.com/ONSdigital/dp-legacy-cache-proxy/tree/feature/proxy-pass-through) on the above PR and run in dp-legacy-cache-proxy make debug
7. Make a request to a Babbage endpoint
8. e.g. http://localhost:20000/economy/environmentalaccounts/bulletins/ukenvironmentalaccounts/2013-06-26
9. HTML content should be returned

### Who can review

Anyone from ONS

2024-03-05 15:42 UTC, jmgq commented on router/router.go
>  		} else {
It's only `/releases/...` that the proxy needs to handle, not `/releasecalendar`.

2024-03-06 12:54 UTC, jmgq commented on router/router.go
> +				router.Handle(cfg.RelCalRoutePrefix+"/releasecalendar", relcal.Handler(cfg.BabbageHandler))
Same thing here.

2024-03-06 12:58 UTC, jmgq commented on router/router.go
> +	} else {
Both blocks of the if/else are identical, except for the handler that's passed to the `Handler` function. That means that you should probably revert these changes and make the handler a variable (if proxy enabled, then handler=proxyHandler, else handler=babbageHandler).

2024-03-06 20:50 UTC, lindenmckenzie requested changes
Would be good to add some basic unit tests for this functionality.

2024-03-07 19:25 UTC, lindenmckenzie submitted a review, later dismissed

2024-03-07 19:25 UTC, lindenmckenzie commented
happy with the changes if the tests pass

2024-03-08 14:37 UTC, jessjenkins approved these changes
Approving as already reviewed by Lindon and tests passed. However I am concerned about the number of mocks that aren't in a `mock` sub-package. Having mocks in their own package helps to avoid identifier collisions between written and generated code and also keeps the written package's API clean from mock specific functions and variables. This problem was not introduced in this PR but it would be very helpful if this issue was addressed in a future PR.

2024-03-08 14:57 UTC, merged